alter table "crawling"."cache" drop constraint "cache_id_key";

alter table "crawling"."cache" drop constraint "cache_pkey";

drop index if exists "crawling"."cache_id_key";

drop index if exists "crawling"."cache_pkey";

drop table "crawling"."cache";


create table "public"."place-info" (
    "id" smallint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "main_photo_url" text default ''::text,
    "score" real default '0'::real,
    "score_count" smallint default '0'::smallint
);


CREATE UNIQUE INDEX "place-info_id_key" ON public."place-info" USING btree (id);

CREATE UNIQUE INDEX "place-info_pkey" ON public."place-info" USING btree (id);

alter table "public"."place-info" add constraint "place-info_pkey" PRIMARY KEY using index "place-info_pkey";

alter table "public"."place-info" add constraint "place-info_id_key" UNIQUE using index "place-info_id_key";

grant delete on table "public"."place-info" to "anon";

grant insert on table "public"."place-info" to "anon";

grant references on table "public"."place-info" to "anon";

grant select on table "public"."place-info" to "anon";

grant trigger on table "public"."place-info" to "anon";

grant truncate on table "public"."place-info" to "anon";

grant update on table "public"."place-info" to "anon";

grant delete on table "public"."place-info" to "authenticated";

grant insert on table "public"."place-info" to "authenticated";

grant references on table "public"."place-info" to "authenticated";

grant select on table "public"."place-info" to "authenticated";

grant trigger on table "public"."place-info" to "authenticated";

grant truncate on table "public"."place-info" to "authenticated";

grant update on table "public"."place-info" to "authenticated";

grant delete on table "public"."place-info" to "service_role";

grant insert on table "public"."place-info" to "service_role";

grant references on table "public"."place-info" to "service_role";

grant select on table "public"."place-info" to "service_role";

grant trigger on table "public"."place-info" to "service_role";

grant truncate on table "public"."place-info" to "service_role";

grant update on table "public"."place-info" to "service_role";


